### ISSUE TITLE
Incorrect code generated for minimum/maximum constraints for 'bandwidth' in contracts model

### ISSUE THREAD

**Issue by kawaja** [telstra/Programmable-Network-SDK-python#2]
In `models/contracts.py` the setter for bandwidth has this code:
https://github.com/telstra/Programmable-Network-SDK-python/blob/35ecde4fe23f1ffb2bdafcb84dec4af1beee95c9/TelstraTPN/models/contract.py#L173-L176

The [OpenAPI spec](https://github.com/telstra/Programmable-Network-API/blob/33e3e5503211c7af68ee467b46cd3cd05e4b39d8/docs/openapi/programmable-network.yaml#L243-L248) has this:
```
    bandwidth.kbs:
      description: "Bandwidth in kB/s"
      type: integer
      example: 1000
      minimum: 1000
      maximum: 10000000
```

There are a few other places where this is wrong, e.g.
https://github.com/telstra/Programmable-Network-SDK-python/blob/35ecde4fe23f1ffb2bdafcb84dec4af1beee95c9/TelstraTPN/models/inventory_link_request.py#L255-L258

Other constraints seem to be generated properly (although `bandwidth` is the only one with a `maxiumum` constraint).
